---
title: "allodb"
resource_files:
- data/dummy_data.rda
- data/wsg_ctfs3.rda
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    horizontal_layout: fill
    navbar:
    - align: right
      href: https://github.com/maurolepore
      icon: fa-gavel
    - align: right
      href: https://github.com/forestgeo/allodb
      icon: fa-github
    orientation: columns
    social: menu
    source_code: embed
    theme: united
    vertical_layout: scroll
---

```{r global, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tibble)
library(stringr)
library(DT)
library(readr)
library(shiny)

# Data --------------------------------------------------------------------

base_dir <- "./data/"
available_datasets <- str_replace(dir(base_dir), ".rda", "")
df_list <- lapply(
  paste0(base_dir, available_datasets, ".rda"), function(x) get(load(x))
) %>% 
  setNames(available_datasets)
```

Inputs {.sidebar}
========================================================================

```{r}
helpText("Choose data set:")
selectInput("dataset", NULL, choices = available_datasets)
df_in <- reactive({
  req(input$dataset)
  df_list[[input$dataset]]
})
```

```{r}
downloadHandler(
  filename = function() {
    paste(input$dataset, ".csv", sep = "")
  },
  content = function(file) {
    readr::write_csv(df_in(), file)
  }
)

renderPrint(
  cat(
    paste0(
      str_pad(1:ncol(df_in()), 2, pad = " "), ": ", names(df_in()), "\n"
    ),
    sep = ""
  )
)
```

```{r}
helpText("Display columns:")
fluidRow(
  column(6, numericInput("var_pos_min", "min", 1)),
  column(6, numericInput("var_pos_max", "max", 6))
)
```

```{r}
helpText("Download these columns:")
df_selected <- reactive({
  req(input$dataset)
  df_in()[input$var_pos_min:input$var_pos_max]
})
downloadHandler(
  filename = function() {
    paste(input$dataset, "_selected", ".csv", sep = "")
  },
  content = function(file) {
    readr::write_csv(df_selected(), file)
  }
)
```

Viewer
========================================================================

```{r}
renderPrint(
  cat("Get help at: ",
    "https://forestgeo.github.io/allodb/reference/", input$dataset, sep = ""
  )
)

renderDataTable({
  req(input$dataset)
  DT::datatable(
    df_selected(),
    filter = 'top',
    options = list(class = 'nowrap display', pageLength = 10),
  )
})
```

