---
title: "allodb"
resource_files:
- data/allo_temperate.rda
- data/ficus.rda
- data/site.info.rda
- data/WSG.rda
- data/wsg_ctfs3.rda
- data/allo_temperate.rda
- data/ficus.rda
- data/site.info.rda
- data/WSG.rda
- data/wsg_ctfs3.rda
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    horizontal_layout: scroll
    orientation: columns
    theme: united
    vertical_layout: fill
---

```{r hide-yml}
# # ymal settings that brake build at work but pass at home.
#    social: menu
#    source_code: embed
#    navbar:
#      - {title: "Code", href: "https://github.com/maurolepore", align: right, 
#        icon: fa-user}
#      - {title: "App", href: "https://github.com/maurolepore", align: right, 
#        icon: fa-user}
```

```{r global, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tibble)
library(stringr)
library(DT)
library(readr)
library(shiny)

# Data --------------------------------------------------------------------

base_dir <- "./data/"
available_datasets <- str_replace(dir(base_dir), ".rda", "")
df_list <- lapply(
  paste0(base_dir, available_datasets, ".rda"), function(x) get(load(x))
) %>% 
  setNames(available_datasets)
```

COLUMN --- {data-width=100}
------------------------------------------------------------------------

### Choose a data set {data-height=40}

```{r}
selectInput("dataset", NULL, choices = available_datasets)
df_in <- reactive({
  req(input$dataset)
  df_list[[input$dataset]]
})
```

```{r}
helpText("Download the entire data set")
downloadHandler(
  filename = function() {
    paste(input$dataset, ".csv", sep = "")
  },
  content = function(file) {
    readr::write_csv(df_in(), file)
  }
)

helpText("Column names")
renderPrint(
  cat(
    paste0(
      str_pad(1:ncol(df_in()), 2, pad = " "), ": ", names(df_in()), "\n"
    ),
    sep = ""
  )
)
```

### Display only these columns (by position) {data-height=20}

```{r}
fluidRow(
  column(6, numericInput("var_pos_min", "min", 1)),
  column(6, numericInput("var_pos_max", "max", 6))
)
```

```{r}
helpText("Download only these columns (all rows)")
df_selected <- reactive({
  req(input$dataset)
  df_in()[input$var_pos_min:input$var_pos_max]
})
downloadHandler(
  filename = function() {
    paste(input$dataset, "_selected", ".csv", sep = "")
  },
  content = function(file) {
    readr::write_csv(df_selected(), file)
  }
)
```

COLUMN --- {data-width=300}
------------------------------------------------------------------------

### Help {data-height=2}

```{r}
renderPrint(
  cat(
    "https://forestgeo.github.io/allodb/reference/", input$dataset, sep = ""
  )
)
```

### Viewer {data-height=100}

```{r}
renderDataTable({
  req(input$dataset)
  DT::datatable(
    df_selected(),
    filter = 'top',
    options = list(class = 'nowrap display', pageLength = 5),
  )
})
```

