---
title: "Meeting at SCBI"
date: "2018-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Meeting report

On 2018-02-27 Erika and Krista and I met at SCBI. These are the topics we covered:

1. Workflow (Erika and Mauro)
    * We reviwed Erika's workflow
    * We ensured that RStudio and GitHub are connected and that Erika's login-credentials don't need to be entered every time she pulls or pushes.

2. Structure of the __allodb__ project (Erika and Mauro)
    * We walked over the details of the structure of the project that should be changed to restore the structure of an R package, so we enjoy the benefits that R packages provide -- such as accesing metadata via help files.
    * We agred that I would make some changes over the following 2 days. Erika will be able to review those changes before accepting them.

3. Pendent issues (Erika, Krista and Mauro)
We discussed and updated open issues.

4. FastField (Erika and Mauro)
We discussed work I've done with Jess Shue in preparation for using the FastField software to collect census data.

5. Overview of __fgeo__ (All of Krista's lab)
I introduced Krista's lab to the __fgeo__ package -- the single place where to look for all things related to ForestGEO's software.


# Pre-meeting

## 1. Project structure and worflow with RStudio and GitHub

### Workflow with RStudio and GitHub

My goal is to design a workflow that is convenient for Erika and makes it easy to integrate her work with that of others.

* What is Erika's workflow?

* What she would like to do that she finds if difficult with her current workflow?

If her workflow would improve with RStudio, connect RStudio and GitHub (see how [here](http://happygitwithr.com/rstudio-git-github.html)).

### Project structure

__allodb__ will be used and shared as an R package. This will be useful for the users, eventually. But do we need to maintain an R package right now? Do we prefer to maintain its structure from this early stage or do we prefer to work more freely now and adapt the project's structure to an R package later? Here are some questions to guide the discussion:

* Do we need an R package?

* What are the advantages and dissavantages now and later?

* Consider the simpler structure of an RStudio project as an alternative.

* How hard it is to transform the current project into an R package?

* How hard it is to maintain an R package?

* What are the resources to help us maintain the structure of an R package (cheetahs, book, etc.)
    * https://github.com/rstudio/cheatsheets/raw/master/package-development.pdf
    * http://r-pkgs.had.co.nz/intro.html

* How can I help maintain whatever structure we believe it's best?

#### Discussion on structure

About the current structure of the project

* How could we change the current structure to make it more suitable for Erika's workflow?

* What is the importance of each directory in the current structure?

* Discuss changes that would make the project more reproducible. May I restructure the project in a new branch for Erika to review? We may merge it to master but only if Erika likes the new structure.

Note: Prominent members of the R community are discussing how to structure research projects (this thread contains many interesting opinions and links: https://github.com/ropensci/unconf17/issues/5; and this article will likely be influential: https://goo.gl/7w4zo6). Some tools are starting to arise (e.g. https://github.com/benmarwick/rrtools) but there is still no consensus.

## 2. FieldForms for census

The work I did is to build an app to help data managers to process the data after the data has been gathered from the field using the FastField software. My work responds directly to requirements by Jess Shue. This video shows how to get and use the app: https://www.youtube.com/watch?v=PN14GGJOVJ4. The app will likely change as the users provide feedback.

